override: false

# ç½‘ç«™favicon
favicon:
  small: /images/favicon.ico

# ç½‘ç«™å…³é”®å­—
keywords: "TyCoding's Blog"

rss:

# ç½‘ç«™åº•éƒ¨
footer:
  # èµ·å§‹æ—¶é—´
  since: 2017

  icon: user
  copyright:
  powered: true

  theme:
    enable: true
    version: true

canonical: true
seo: false
index_with_subtitle: false

# ç½‘ç«™Headerå¯¼èˆªé¡µ
menu:
  home: /
  archives: /archives/
  about: /about/
  links: /links/

# ç½‘ç«™ç½®é¡¶é“¾æ¥
top:
  links: 
    'ğŸ¤SpringCloudåˆ†å¸ƒå¼é¡¹ç›®è„šæ‰‹æ¶': 'https://github.com/TyCoding/cloud-template'


menu_icons:
  enable: true

# ä»…æ”¯æŒè®¾å®šçš„Tumoä¸»é¢˜ï¼Œå…¶ä»–çš„Nextä¸»é¢˜ç”±äºæ²¡æœ‰é€‚é…å°±åˆ é™¤äº†
scheme: Tumo

# Sidebar å³ä¾§é“¾æ¥å¯¼èˆªé¡µã€‚ `|| `è·Ÿéšfont-awesomeçš„å›¾æ ‡åç§°
social:
  GitHub: https://github.com/TyCoding || github
  Tumo: https://github.com/TyCoding/tumo || link
  SpringCloud: https://github.com/TyCoding/cloud-template || cloud

social_icons:
  enable: true
  icons_only: false
  transition: false

# Sidebar å¤´åƒ
avatar: /images/avatar.jpg

# Sidebar Toc
toc:
  enable: true
  number: true
  wrap: false

# Sidebarä½ç½®
sidebar:
  position: left
  display: always
  offset: 12
  b2t: false
  scrollpercent: false
  onmobile: false

scroll_to_more: true
save_scroll: false
excerpt_description: true

auto_excerpt:
  enable: false
  length: 150

post_meta:
  item_text: true
  created_at: true
  updated_at: false
  categories: true

post_wordcount:
  item_text: true
  wordcount: false
  min2read: false
  totalcount: false
  separated_meta: true


# å¾®ä¿¡å…¬ä¼—å·
wechat_subscriber:
  enabled: true
  qcode: /images/qrcode_for_gh.jpg
  description: æ¬¢è¿å…³æ³¨å…¬ä¼—å·ï¼šç¨‹åºå‘˜æ¶‚é™Œ

# æ‰“èµ
reward_comment: å¦‚æœä½ è§‰å¾—è¿™ç¯‡æ–‡ç« å¸®åŠ©åˆ°äº†ä½ ï¼Œä½ å¯ä»¥å¸®ä½œè€…ä¹°ä¸€æ¯æœæ±è¡¨ç¤ºé¼“åŠ± 
wechatpay: /images/wechat.png
alipay: /images/alipay.png

# ç‰ˆæƒå£°æ˜
post_copyright:
  enable: false
  license: CC BY-NC-SA 3.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/3.0/

mobile_layout_economy: false
android_chrome_color: "#222"

custom_logo:
  enabled: false
  image:

# ä»£ç é«˜äº®ä¸»é¢˜
highlight_theme: normal

# å­—ä½“è®¾ç½®
font:
  enable: false
  host:
  global:
    external: true
    family: Lato
    size:
  headings:
    external: true
    family:
    size:
  posts:
    external: true
    family:
  logo:
    external: true
    family:
    size:
  codes:
    external: true
    family:
    size:

# Markdownæ•°å­¦å…¬å¼æ”¯æŒ
mathjax:
  enable: false
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML

han: false

# Disqus
disqus:
  enable: false
  shortname:
  count: true

# Hypercomments
#hypercomments_id:

# changyan
changyan:
  enable: false
  appid:
  appkey:

# Valine. è¯„è®ºæ’ä»¶
valine:
  enable: true
  appid:   # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size

gitment:
  enable: false
  mint: true # RECOMMEND, A mint on Gitment, to support count, language and proxy_gateway
  count: true # Show comments count in post meta area
  lazy: false # Comments lazy loading with a button
  cleanly: false # Hide 'Powered by ...' on footer, and more
  language: # Force language, or auto switch by theme
  github_user: # MUST HAVE, Your Github ID
  github_repo: # MUST HAVE, The repo you use to store Gitment comments
  client_id: # MUST HAVE, Github client id for the Gitment
  client_secret: # EITHER this or proxy_gateway, Github access secret token for the Gitment
  proxy_gateway: # Address of api proxy, See: https://github.com/aimingoo/intersect
  redirect_protocol: # Protocol of redirect_uri with force_redirect_protocol when mint enabled

# NeedMoreShare2
needmoreshare2:
  enable: false
  postbottom:
    enable: false
    options:
      iconStyle: box
      boxForm: horizontal
      position: bottomCenter
      networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook
  float:
    enable: false
    options:
      iconStyle: box
      boxForm: horizontal
      position: middleRight
      networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook

duoshuo_info:
  ua_enable: true
  admin_enable: false
  user_id: 0
  #admin_nickname: Author
# Facebook SDK Support.
facebook_sdk:
  enable:       false
  app_id:       #<app_id>
  fb_admin:     #<user_id>
  like_button:  #true
  webmaster:    #true

# Facebook comments plugin
# This plugin depends on Facebook SDK.
# If facebook_sdk.enable is false, Facebook comments plugin is unavailable.
facebook_comments_plugin:
  enable:       false
  num_of_posts: 10    # min posts num is 1
  width:        100%  # default width is 550px
  scheme:       light # default scheme is light (light or dark)

# VKontakte API Support.
# To get your AppID visit https://vk.com/editapp?act=create
vkontakte_api:
  enable:       false
  app_id:       #<app_id>
  like:         true
  comments:     true
  num_of_posts: 10

rating:
  enable: false
  id:     #<app_id>
  color:  fc6423

leancloud_visitors:
  enable: false
  app_id: #<app_id>
  app_key: #<app_key>

firestore:
  enable: false
  collection: articles #required, a string collection name to access firestore database
  apiKey: #required
  projectId: #required
  bluebird: false #enable this if you want to include bluebird 3.5.1(core version) Promise polyfill

# ä¸è’œå­ç»Ÿè®¡
busuanzi_count:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: UV
  site_uv_footer:
  # custom pv span for the whole site
  site_pv: true
  site_pv_header: PV
  site_pv_footer:
  # custom pv span for one page only
  page_pv: false
  page_pv_header: <i class="fa fa-file-o"></i>
  page_pv_footer:

# Enable baidu push so that the blog will push the url to baidu automatically which is very helpful for SEO
baidu_push: false

calendar:
  enable: false
  calendar_id: <required>
  api_key: <required>
  orderBy: startTime
  offsetMax: 24
  offsetMin: 4
  timeZone:
  showDeleted: false
  singleEvents: true
  maxResults: 250

# Algolia Search
algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"

# æœ¬åœ°æœç´¢ï¼Œéœ€è¦åœ¨ç½‘ç«™æ ¹ç›®å½•ï¼ˆéthemesæ ¹ç›®å½•ï¼‰ä¸‹æ–°å»ºä¸€ä¸ªç©ºçš„ search.xml æ–‡ä»¶
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1

exturl: false

note:
  style: simple
  icons: false
  border_radius: 3
  light_bg_offset: 0

# Label tag.
label: true

# Tabs tag.
tabs:
  enable: true
  transition:
    tabs: false
    labels: true
  border_radius: 0

# åŠ¨æ€æ•ˆæœ
motion:
  enable: false
  async: false
  transition:
    post_block: fadeIn
    post_header: slideDownIn
    post_body: slideDownIn
    coll_header: slideLeftIn
    # Only for Pisces | Gemini.
    sidebar: slideUpIn

# Fancybox
fancybox: true

pace: false
pace_theme: pace-theme-minimal
canvas_nest: false
three_waves: false
canvas_lines: false
canvas_sphere: false
canvas_ribbon:
  enable: false
  size: 300
  alpha: 0.6
  zIndex: -1

# æ’ä»¶æ”¯æŒ
vendors:
  # Internal path prefix. Please do not edit it.
  _internal: lib

  # Internal version: 2.1.3
  jquery:

  # Internal version: 2.1.5
  # See: http://fancyapps.com/fancybox/
  fancybox:
  fancybox_css:

  # Internal version: 1.0.6
  # See: https://github.com/ftlabs/fastclick
  fastclick:

  # Internal version: 1.9.7
  # See: https://github.com/tuupola/jquery_lazyload
  lazyload:

  # Internal version: 1.2.1
  # See: http://VelocityJS.org
  velocity:

  # Internal version: 1.2.1
  # See: http://VelocityJS.org
  velocity_ui:

  # Internal version: 0.7.9
  # See: https://faisalman.github.io/ua-parser-js/
  ua_parser:

  # Internal version: 4.6.2
  # See: http://fontawesome.io/
  fontawesome:

  # Internal version: 1
  # https://www.algolia.com
  algolia_instant_js:
  algolia_instant_css:

  # Internal version: 1.0.2
  # See: https://github.com/HubSpot/pace
  # Or use direct links below:
  # pace: //cdn.bootcss.com/pace/1.0.2/pace.min.js
  # pace_css: //cdn.bootcss.com/pace/1.0.2/themes/blue/pace-theme-flash.min.css
  pace:
  pace_css:

  # Internal version: 1.0.0
  # https://github.com/hustcc/canvas-nest.js
  canvas_nest:

  # three
  three:

  # three_waves
  # https://github.com/jjandxa/three_waves
  three_waves:

  # three_waves
  # https://github.com/jjandxa/canvas_lines
  canvas_lines:

  # three_waves
  # https://github.com/jjandxa/canvas_sphere
  canvas_sphere:

  # Internal version: 1.0.0
  # https://github.com/zproo/canvas-ribbon
  canvas_ribbon:

  # Internal version: 3.3.0
  # https://github.com/ethantw/Han
  han:

  # needMoreShare2
  # https://github.com/revir/need-more-share2
  needMoreShare2:

# Assets
css: css
js: js
images: images

# Theme version
version: 5.1.4